name: KADATMC-KEEP-ALIVE

on:
  workflow_dispatch: # Cho phép bạn bấm nút Run thủ công

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start Minecraft Bot
        run: node bot.js
